# Generated by Django 4.2.3 on 2023-07-19 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='bio',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
