# Generated by Django 4.2.3 on 2023-07-26 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_followerscount_likepost_post_profile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddressInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=300)),
            ],
        ),
    ]
