# Generated by Django 4.2.3 on 2023-08-04 03:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='repost',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='repost_notifications', to='core.post'),
        ),
        migrations.AddField(
            model_name='notification',
            name='usercomment',
            field=models.ForeignKey(default='', max_length=200, on_delete=django.db.models.deletion.CASCADE, related_name='comment_notifications', to='core.post'),
        ),
        migrations.RemoveField(
            model_name='notification',
            name='likeby',
        ),
        migrations.AddField(
            model_name='notification',
            name='likeby',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='like_notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
