# Generated by Django 4.2.2 on 2023-08-31 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_notification_repost_notification_usercomment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='likepost',
            name='no_of_likes',
            field=models.IntegerField(default=0),
        ),
    ]
