# Generated by Django 4.2.2 on 2023-08-31 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_likepost_no_of_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='num_of_likes',
            new_name='no_of_likes',
        ),
    ]
